import { randomUUID } from "node:crypto";
import { constants } from "node:fs";
import { lstat, mkdir, open, realpath, rename } from "node:fs/promises";
import path from "node:path";

import { CODEX_VERSION, FORGE_MCP_MODULE, type CodexRuntime } from "./runtime-manifest";

const WORKSPACE_ID_PATTERN = /^[a-z][a-z0-9_-]{1,63}$/u;
const FORGE_TOOLS = Object.freeze([
  "forge_stage_changeset",
  "forge_get_changeset",
  "forge_list_changesets",
]);

export interface CodexConfigOptions {
  runtime: CodexRuntime;
  codexHome: string;
  dataDir: string;
  workspaceId: string;
  workspaceRoot: string;
  environment?: NodeJS.ProcessEnv;
}

export interface CodexLaunchSpec {
  executable: string;
  args: readonly ["app-server", "--stdio", "--strict-config"];
  cwd: string;
  env: Readonly<Record<string, string>>;
  codexHome: string;
  configPath: string;
  workspaceId: string;
  expectedVersion: typeof CODEX_VERSION;
}

export async function prepareCodexLaunch(options: CodexConfigOptions): Promise<CodexLaunchSpec> {
  assertWorkspaceId(options.workspaceId);
  const codexHome = await ensurePrivateDirectory(options.codexHome, "Codex home");
  const workspaceRoot = await canonicalDirectory(options.workspaceRoot, "Forge workspace root");
  const dataDir = await canonicalDirectory(options.dataDir, "Forge service data directory");
  const pythonExecutable = await canonicalFile(
    options.runtime.pythonExecutable,
    "Forge MCP Python interpreter",
  );
  const codexExecutable = await canonicalFile(options.runtime.codexExecutable, "Codex executable");

  const configPath = path.join(codexHome, "config.toml");
  await atomicWritePrivateFile(
    configPath,
    renderConfig(pythonExecutable, dataDir, options.workspaceId),
  );

  return Object.freeze({
    executable: codexExecutable,
    args: Object.freeze(["app-server", "--stdio", "--strict-config"] as const),
    cwd: workspaceRoot,
    env: Object.freeze(sanitizedCodexEnvironment(codexHome, options.environment ?? process.env)),
    codexHome,
    configPath,
    workspaceId: options.workspaceId,
    expectedVersion: CODEX_VERSION,
  });
}

function renderConfig(pythonExecutable: string, dataDir: string, workspaceId: string): string {
  const command = tomlString(pythonExecutable);
  const args = [
    "-I",
    "-m",
    FORGE_MCP_MODULE,
    "--data-dir",
    dataDir,
    "--workspace-id",
    workspaceId,
  ].map(tomlString);
  const tools = FORGE_TOOLS.map(tomlString);
  return [
    '# Generated by RPG World Forge Studio. Do not edit while Studio is running.',
    'approval_policy = "never"',
    'sandbox_mode = "read-only"',
    'web_search = "disabled"',
    'check_for_update_on_startup = false',
    'disable_response_storage = true',
    '',
    '[analytics]',
    'enabled = false',
    '',
    '[shell_environment_policy]',
    'inherit = "none"',
    '',
    '[features]',
    'shell_snapshot = false',
    '',
    '[mcp_servers.forge]',
    `command = ${command}`,
    `args = [${args.join(", ")}]`,
    'enabled = true',
    'required = true',
    `enabled_tools = [${tools.join(", ")}]`,
    'startup_timeout_sec = 10',
    'tool_timeout_sec = 30',
    '',
  ].join("\n");
}

function sanitizedCodexEnvironment(
  codexHome: string,
  source: NodeJS.ProcessEnv,
): Record<string, string> {
  const result: Record<string, string> = {
    CODEX_HOME: codexHome,
    HOME: codexHome,
    USERPROFILE: codexHome,
    APPDATA: codexHome,
    LOCALAPPDATA: codexHome,
  };
  for (const name of ["LANG", "LC_ALL", "SYSTEMROOT", "TEMP", "TMP", "WINDIR"]) {
    const value = source[name];
    if (value && !containsControl(value)) {
      result[name] = value;
    }
  }
  return result;
}

async function ensurePrivateDirectory(value: string, label: string): Promise<string> {
  assertAbsolutePath(value, label);
  await mkdir(value, { recursive: true, mode: 0o700 });
  const info = await lstat(value);
  if (!info.isDirectory() || info.isSymbolicLink()) {
    throw new Error(`${label} must be a standalone directory`);
  }
  const canonical = await realpath(value);
  if (canonical !== path.resolve(value)) {
    throw new Error(`${label} identity is not canonical`);
  }
  return canonical;
}

async function canonicalDirectory(value: string, label: string): Promise<string> {
  assertAbsolutePath(value, label);
  const info = await lstat(value);
  if (!info.isDirectory() || info.isSymbolicLink()) {
    throw new Error(`${label} must be a standalone directory`);
  }
  const canonical = await realpath(value);
  if (canonical !== path.resolve(value)) {
    throw new Error(`${label} identity is not canonical`);
  }
  return canonical;
}

async function canonicalFile(value: string, label: string): Promise<string> {
  assertAbsolutePath(value, label);
  const info = await lstat(value);
  if (!info.isFile() && !info.isSymbolicLink()) {
    throw new Error(`${label} must be a file`);
  }
  const canonical = await realpath(value);
  const target = await lstat(canonical);
  if (!target.isFile()) {
    throw new Error(`${label} must resolve to a regular file`);
  }
  return canonical;
}

async function atomicWritePrivateFile(filename: string, content: string): Promise<void> {
  const directory = path.dirname(filename);
  const temporary = path.join(directory, `.config.${randomUUID()}.tmp`);
  const bytes = Buffer.from(content, "utf8");
  let handle;
  try {
    handle = await open(
      temporary,
      constants.O_CREAT | constants.O_EXCL | constants.O_WRONLY | constants.O_NOFOLLOW,
      0o600,
    );
    const info = await handle.stat();
    if (!info.isFile() || info.nlink !== 1) {
      throw new Error("Codex configuration temporary file identity is unsafe");
    }
    await handle.writeFile(bytes);
    await handle.sync();
    await handle.close();
    handle = undefined;
    try {
      const current = await lstat(filename);
      if (!current.isFile() || current.isSymbolicLink() || current.nlink !== 1) {
        throw new Error("Existing Codex configuration identity is unsafe");
      }
    } catch (error) {
      if (!isMissing(error)) {
        throw error;
      }
    }
    await rename(temporary, filename);
    const published = await lstat(filename);
    if (!published.isFile() || published.isSymbolicLink() || published.nlink !== 1) {
      throw new Error("Published Codex configuration identity is unsafe");
    }
    await syncDirectory(directory);
  } finally {
    await handle?.close().catch(() => undefined);
    const { rm } = await import("node:fs/promises");
    await rm(temporary, { force: true }).catch(() => undefined);
  }
}

async function syncDirectory(directory: string): Promise<void> {
  let handle;
  try {
    handle = await open(directory, constants.O_RDONLY);
    await handle.sync();
  } catch (error) {
    if (process.platform !== "win32") {
      throw error;
    }
  } finally {
    await handle?.close().catch(() => undefined);
  }
}

function tomlString(value: string): string {
  if (containsControl(value)) {
    throw new TypeError("Codex configuration values must not contain control characters");
  }
  return JSON.stringify(value);
}

function assertWorkspaceId(value: string): void {
  if (!WORKSPACE_ID_PATTERN.test(value)) {
    throw new TypeError("Forge workspace ID is invalid");
  }
}

function assertAbsolutePath(value: string, label: string): void {
  if (!path.isAbsolute(value) || containsControl(value)) {
    throw new TypeError(`${label} must be an absolute path without control characters`);
  }
}

function containsControl(value: string): boolean {
  return [...value].some((character) => {
    const code = character.codePointAt(0);
    return code !== undefined && (code <= 0x1f || code === 0x7f);
  });
}

function isMissing(error: unknown): boolean {
  return isNodeError(error) && error.code === "ENOENT";
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && "code" in error;
}
