from __future__ import annotations

WORKER_PROTOCOL = "rpg-world-forge.studio_worker"
LEGACY_WORKER_VERSION = 1
WORKER_VERSION = 2
MAX_WORKER_REQUEST_BYTES = 64 * 1024
MAX_WORKER_RESPONSE_BYTES = 1024 * 1024
